helm repo add grafana https://grafana.github.io/helm-charts &&
  helm repo update &&
  helm upgrade --install --atomic --timeout 300s grafana-k8s-monitoring grafana/k8s-monitoring \
    --namespace "default" --create-namespace --values - <<'EOF'
cluster:
  name: my-ocpcluster
destinations:
  - name: grafana-cloud-metrics
    type: prometheus
    url: https://prometheus-prod-24-prod-eu-west-2.grafana.net./api/prom/push
    auth:
      type: basic
      username: "2560731"
      password: glc_eyJvIjoiMTQzMDg2MSIsIm4iOiJzdGFjay0xMzE4MjQ4LWludGVncmF0aW9uLW15LW9jcHRva2VuLW15LW9jcHRva2VuIiwiayI6IjR2ODRkMVRlc2szek0wSHMxMzJpUWtvMyIsIm0iOnsiciI6InByb2QtZXUtd2VzdC0yIn19
  - name: grafana-cloud-logs
    type: loki
    url: https://logs-prod-012.grafana.net./loki/api/v1/push
    auth:
      type: basic
      username: "1276042"
      password: glc_eyJvIjoiMTQzMDg2MSIsIm4iOiJzdGFjay0xMzE4MjQ4LWludGVncmF0aW9uLW15LW9jcHRva2VuLW15LW9jcHRva2VuIiwiayI6IjR2ODRkMVRlc2szek0wSHMxMzJpUWtvMyIsIm0iOnsiciI6InByb2QtZXUtd2VzdC0yIn19
  - name: grafana-cloud-otlp-endpoint
    type: otlp
    url: https://otlp-gateway-prod-eu-west-2.grafana.net./otlp
    protocol: http
    auth:
      type: basic
      username: "1318248"
      password: glc_eyJvIjoiMTQzMDg2MSIsIm4iOiJzdGFjay0xMzE4MjQ4LWludGVncmF0aW9uLW15LW9jcHRva2VuLW15LW9jcHRva2VuIiwiayI6IjR2ODRkMVRlc2szek0wSHMxMzJpUWtvMyIsIm0iOnsiciI6InByb2QtZXUtd2VzdC0yIn19
    metrics:
      enabled: true
    logs:
      enabled: true
    traces:
      enabled: true
global:
  platform: openshift
clusterMetrics:
  enabled: true
  opencost:
    enabled: true
    metricsSource: grafana-cloud-metrics
    opencost:
      exporter:
        defaultClusterId: my-ocpcluster
      prometheus:
        existingSecretName: grafana-cloud-metrics-grafana-k8s-monitoring
        external:
          url: https://prometheus-prod-24-prod-eu-west-2.grafana.net./api/prom
  kepler:
    enabled: true
  node-exporter:
    enabled: true
    deploy: false
    namespace: openshift-monitoring
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    service:
      scheme: https
      portName: https
  kube-state-metrics:
    enabled: true
    deploy: false
    namespace: openshift-monitoring
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    service:
      scheme: https
      portName: https-main
annotationAutodiscovery:
  enabled: true
prometheusOperatorObjects:
  enabled: true
clusterEvents:
  enabled: true
podLogs:
  enabled: true
applicationObservability:
  enabled: true
  receivers:
    otlp:
      grpc:
        enabled: true
        port: 4317
      http:
        enabled: true
        port: 4318
    zipkin:
      enabled: true
      port: 9411
  connectors:
    grafanaCloudMetrics:
      enabled: true
autoInstrumentation:
  enabled: true
alloy-metrics:
  enabled: true
  alloy:
    extraEnv:
      - name: GCLOUD_RW_API_KEY
        valueFrom:
          secretKeyRef:
            name: alloy-metrics-remote-cfg-grafana-k8s-monitoring
            key: password
      - name: CLUSTER_NAME
        value: my-ocpcluster
      - name: NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: GCLOUD_FM_COLLECTOR_ID
        value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-$(POD_NAME)
  remoteConfig:
    enabled: true
    url: https://fleet-management-prod-011.grafana.net
    auth:
      type: basic
      username: "1318248"
      password: glc_eyJvIjoiMTQzMDg2MSIsIm4iOiJzdGFjay0xMzE4MjQ4LWludGVncmF0aW9uLW15LW9jcHRva2VuLW15LW9jcHRva2VuIiwiayI6IjR2ODRkMVRlc2szek0wSHMxMzJpUWtvMyIsIm0iOnsiciI6InByb2QtZXUtd2VzdC0yIn19
alloy-singleton:
  enabled: true
  alloy:
    extraEnv:
      - name: GCLOUD_RW_API_KEY
        valueFrom:
          secretKeyRef:
            name: alloy-singleton-remote-cfg-grafana-k8s-monitoring
            key: password
      - name: CLUSTER_NAME
        value: my-ocpcluster
      - name: NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: GCLOUD_FM_COLLECTOR_ID
        value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-$(POD_NAME)
  remoteConfig:
    enabled: true
    url: https://fleet-management-prod-011.grafana.net
    auth:
      type: basic
      username: "1318248"
      password: glc_eyJvIjoiMTQzMDg2MSIsIm4iOiJzdGFjay0xMzE4MjQ4LWludGVncmF0aW9uLW15LW9jcHRva2VuLW15LW9jcHRva2VuIiwiayI6IjR2ODRkMVRlc2szek0wSHMxMzJpUWtvMyIsIm0iOnsiciI6InByb2QtZXUtd2VzdC0yIn19
alloy-logs:
  enabled: true
  global:
    podSecurityContext:
      seLinuxOptions:
        type: container_logreader_t
  alloy:
    extraEnv:
      - name: GCLOUD_RW_API_KEY
        valueFrom:
          secretKeyRef:
            name: alloy-logs-remote-cfg-grafana-k8s-monitoring
            key: password
      - name: CLUSTER_NAME
        value: my-ocpcluster
      - name: NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      - name: GCLOUD_FM_COLLECTOR_ID
        value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-alloy-logs-$(NODE_NAME)
  remoteConfig:
    enabled: true
    url: https://fleet-management-prod-011.grafana.net
    auth:
      type: basic
      username: "1318248"
      password: glc_eyJvIjoiMTQzMDg2MSIsIm4iOiJzdGFjay0xMzE4MjQ4LWludGVncmF0aW9uLW15LW9jcHRva2VuLW15LW9jcHRva2VuIiwiayI6IjR2ODRkMVRlc2szek0wSHMxMzJpUWtvMyIsIm0iOnsiciI6InByb2QtZXUtd2VzdC0yIn19
alloy-receiver:
  enabled: true
  alloy:
    extraPorts:
      - name: otlp-grpc
        port: 4317
        targetPort: 4317
        protocol: TCP
      - name: otlp-http
        port: 4318
        targetPort: 4318
        protocol: TCP
      - name: zipkin
        port: 9411
        targetPort: 9411
        protocol: TCP
    extraEnv:
      - name: GCLOUD_RW_API_KEY
        valueFrom:
          secretKeyRef:
            name: alloy-receiver-remote-cfg-grafana-k8s-monitoring
            key: password
      - name: CLUSTER_NAME
        value: my-ocpcluster
      - name: NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      - name: GCLOUD_FM_COLLECTOR_ID
        value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-alloy-receiver-$(NODE_NAME)
  remoteConfig:
    enabled: true
    url: https://fleet-management-prod-011.grafana.net
    auth:
      type: basic
      username: "1318248"
      password: glc_eyJvIjoiMTQzMDg2MSIsIm4iOiJzdGFjay0xMzE4MjQ4LWludGVncmF0aW9uLW15LW9jcHRva2VuLW15LW9jcHRva2VuIiwiayI6IjR2ODRkMVRlc2szek0wSHMxMzJpUWtvMyIsIm0iOnsiciI6InByb2QtZXUtd2VzdC0yIn19
EOF
